### ISSUE TITLE
Better auto-PR set up

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/interactive-templates#118]

**Comment by bloodearnest** [comment]
The auto PR from interactive_templates to job-server is currently using a personal fine grained token from me in order to be able to run the PR workflows automatically.

This is not ideal, as a) it's a personal token b) means I can't +1 the PR and c) it expires and is security complexity.

Databuilder does this by requiring devs to close and then reop the PR, which will run the checks, and avoids the need for any tokens.

The problem with that is that it is cumbersome, and not visible.

One possible solution is to automatically post the PR link to #tech-code-reviews slack channel. This would allow folk to go do the close/reopen dance.

Worth trying?

**Comment by StevenMaude** [comment]
Moved the workflow to job-server which removes the requirement for the personal access token[^1]; we can reconsider using Slack to open code reviews in future, if necessary.

In practice, the number of updates to this repository has been few and far between: we've only had two releases under the current process (using the `version` file) to date.

[^1]: In line with the issues of personal access tokens as discussed in ebmdatalab/metrics#194.
