### ISSUE TITLE
Fix dependabot security alerts

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/interactive-templates#362]
Ben pointed out that we have 17 security alerts on this repo:
https://github.com/opensafely-core/interactive-templates/security/dependabot  

We should update the affected libraries. I think Dependabot may not be picking up updates to production libraries, only dev ones, so this will need a manual upgrade rather than just merging the existing PRs.

**Comment by Jongmassey** [comment]
I've been through the existing dependabot PRs to hopefully make this a bit simpler
