### ISSUE TITLE
Python 3.8/3.11

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/interactive-templates#423]
`just test`, which is run by the CI/test workflow, has `requirements-unit` in its dependency tree. `requirements-unit` compiles `requirements.unit.in` on a Docker container built from python:latest. In other words, against Python 3.8. However, `requirements.dev.in` and `pyproject.toml` are compiled against Python 3.11, both when running `just [prodenv|devenv]` and by Dependabot (because of `.python-version`).

Until recently, this confusing situation was just about ignorable. Occasionally `requirements-unit` would fail because a transitive dependency didn't have a hash, but we fixed it by making the transitive dependency a direct dependency (e.g. exceptiongroup). However, Python 3.8 was retired on 2024-10-07 and at least one dependency, hypothesis, no longer supports it.

Is this confusing situation still just about ignorable? Dependabot compiles `requirements.unit.in`, `requirements.dev.in`, and `pyproject.toml` against Python 3.11. But the subsequent run of the CI/test workflow fails, because `requirements-unit` attempts to compile `requirements.unit.in`, but no version of hypothesis supports Python 3.8. "Fine", I hear you say, "Let's just pin hypothesis in `requirements.unit.in`". Well, dear reader, I can't, because:

```
TypeError: __init__() takes 2 positional arguments but 3 were given
```

This is at the end of a stack trace that's all about pip-tools.

I'd argue that this confusing situation is no longer ignorable, but also not worth fixing, given that OSI is looking forward to spending more time with the grandchildren. I worked around it recently by removing `requirements.dev.in` from Dependabot's PR (#422).

**Comment by iaindillingham** [comment]
Just to add that it's not possible to instruct Dependabot to ignore `requirements.unit.in`. (It is possible to instruct Dependabot to [ignore individual dependencies](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore), though.)

**Comment by lucyb** [comment]
I agree, we don't won't to spend time fixing this at the moment. I'm closing the issue because I don't think anything needs to be done, but please reopen if that's wrong.

**Comment by iaindillingham** [comment]
If nothing is done @lucyb, then every week the person on the Dependabot rota will have to either close the PR on `requirements.unit.txt` without merging; or rework the PR on `requirements.unit.txt` and `requirements.dev.in`, such that the former doesn't bump hypothesis but the latter does.

Given that OSI is pondering a Saga cruise, I'd suggest that we ignore the hypothesis dependency everywhere, by updating `.github/dependabot.yml`. I'm going to reopen the issue, with that in mind.
