### ISSUE TITLE
Test how long the new analysis will take to run with different time frames

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/interactive-templates#6]
It would be useful to know whether having a longer or shorter time frame for looking for occurrences of codes from codelist B will affect how long the overall query takes to run.

Suggested time frames to test with:
1. In the last 2 years
2. In the last 5 years
3. Has ever had the code added

The information from this test will be used to decide what options to allow users to select from.

**Comment by lucyb** [comment]
Louis will pick up as part of the medication review repo

**Comment by LFISHER7** [comment]
I've now run a selection of analyses using different comparison periods. Each run was made up of 12 monthly extracts, which hopefully smooths out some variability in runtime. The results of this are below:

- [Ever](https://jobs.opensafely.org/datalab/what-was-the-impact-of-the-covid-19-pandemic-on-medication-reviews/medication_reviews/15996/x6nnykkfrznzacq5/) - 1hr 06min
- [5 years](https://jobs.opensafely.org/datalab/what-was-the-impact-of-the-covid-19-pandemic-on-medication-reviews/medication_reviews/16017/zxmpvp2llzfaycq4/) - 1hr 05min
- [2 years](https://jobs.opensafely.org/datalab/what-was-the-impact-of-the-covid-19-pandemic-on-medication-reviews/medication_reviews/16052/cucjvrihb5vofn64/) - 1hr 11min
- [1 month](https://jobs.opensafely.org/datalab/what-was-the-impact-of-the-covid-19-pandemic-on-medication-reviews/medication_reviews/16036/fhq7pnpvh45f2l27/) - 1hr 29min

My conclusion from this is that it doesn't make any difference from a performance perspective if we choose to offer a 5 year lookback or an "ever had" look back. Given "ever had" will be preferable for capturing historic conditions, we should probably offer this.
