### ISSUE TITLE
Update END_DATE to be the last complete month

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/interactive-templates#60]
As we're only grouping by month at the moment, the END_DATE should be the date of the last complete month that we have data for.

See #17 for related changes to WEEK_OF_LATEST_EXTRACT

Acceptance criteria:
* The END_DATE should be calculated using the current [date_of_last_extract()](https://github.com/opensafely-core/job-server/blob/e6410db48e209dd42f38344990413c2f50aaa412/interactive/dates.py#L5-L15) function and then reduced to the last complete month. i.e if `date_of_last_extract()` returns 06-APR-2023, then the `END_DATE` would be set to 31-MAR-2023.

**Comment by ghickman** [comment]
Done in opensafely-core/job-server#2955
